### ISSUE TITLE
Handy-App

### ISSUE THREAD

**Issue by neuhaus** [Kennzeichen-Scan/Enttarnen#1]
Mehr ein FAQ als ein Issue:

Kann eine typische Smartphone-Kamera diese Infrarot-Blitze ebenfalls erkennen? Dann wäre doch auch eine Handy-App denkbar. Gibt ja auch schon Apps um Gewitterblitze zu fotografieren.

**Comment by Scan-Rec** [comment]
Hallo neuhaus,

Handykameras gehen auch. Es hängt sehr vom Modell ab. Hast du dir die entsprechende Wikiseite https://github.com/Scan-Rec/Scan-Rec/wiki/Weitere-einfache-Erkennungsm%C3%B6glichkeiten#nutzung-von-smartphones-oder-webcams dazu mal angesehen?

Eine spezielle App brauchst du nicht, die normale Videokameraaufzeichnung ist ausreichend. Wie im Wiki beschrieben, einfach mal an einer Mautbrücke testen. Siehe dazu https://github.com/Scan-Rec/Scan-Rec/wiki/Automatisierte-Erkennung#mautbr%C3%BCcken-als-testobjekte
